### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by g-izzc** [TheHandyUser/imange#1]
The README.md doesn't have a documentation. How would I know on how I use it?

**Comment by codeaye** [comment]
I have just uploaded a documentation. Thanks for reaching out i completely forgot about the documentation .. Anyway after reading that if you still have any doubts please do ask until then im closing this. Cheers!

**Comment by codeaye** [comment]
[Here](https://www.npmjs.com/package/imange/v/1.0.4) if you want to view it in npmjs
